train_dir: '../data/cmu/train'
test_dir: '../data/cmu/test'
work_dir: './work_dir/prediction'

actions: 'all'
batch_size: 32
source_seq_len: 50
target_seq_len: 10
        

model: net.model.Model
model_args:
  n_in_enc: 3
  n_hid_enc: 256
  n_in_dec: 9
  n_hid_dec: 256
  fusion_layer: 2
  cross_w: 0.3
  scales_mode: '123'
  graph_args_j:
    layout: 'cmu'
    strategy: 'distance'
  graph_args_p:
    layout: 'cmu'
    strategy: 'distance'
  graph_args_b:
    layout: 'cmu'
    strategy: 'distance'
edge_weighting: True


iter_num: 20000
weight_decay: 0.0001
optimizer: 'Adam'
step: [1000,  2000,  3000,  4000, 5000, 6000, 7000, 8000, 9000, 10000, 11000, 12000, 13000, 14000, 15000, 16000, 17000, 18000, 19000, 19990]
base_lr: 0.00005
use_gpu: True
device: [1]

lamda: 0.6
fusion_layer_dir: fusion_2
learning_rate_dir: adam_1e-4
lamda_dir: lamda_06
crossw_dir: cross_03  
note: test

debug: False
